### ISSUE TITLE
datafield "URL" only accepts FQDNs

### ISSUE THREAD

**Issue by SvenRoederer** [berliCRM/berlicrm#16]
For our organization I added a field to the Tickets-View where we can put a link for our bug-tracking-system. 
They have the form ```http://bugtracker/issue/x```. This hostname will not be accepted by the CRM, I must change it to ```http://bugtracker.intern.my-company.de/issue/x``` to get accepted.

Can the requirement for the FQDN in links be removed?

**Comment by urban-thinking** [comment]
Hiya,

it's implemented by a (very usefull) validation library on top of jQuery ... WE like to check, if a URL is valid. If you have other ideas, you could modify it to your needs in `libraries/jquery/posabsolute-jQuery-Validation-Engine/js/jquery.validationEngine-en.js` ...

kind regards
