### ISSUE TITLE
Can't Create the Servicecontract

### ISSUE THREAD

**Issue by BastyJuice** [berliCRM/berlicrm#163]
It is not possible to Create a Newservicecontract at the moment, the procedure will finisch and the number wil change but no entry in the list also in db will this entry not written

**Comment by Archibald111** [comment]
this is not correct, you can try it out at https://berlicrmdemo.co.crm-now.de/

**Comment by BastyJuice** [comment]
Your Demo ist an older Code try it with the Latest GITCODE from Reposotory

**Comment by BastyJuice** [comment]
02/17/19 09:13:50,315 [22356] INFO VT  - PearDatabase ->ADODB error  Query Failed:insert into vtiger_servicecontracts(servicecontractsid,start_date,sc_related_to,tracking_unit,total_units,used_units,subject,due_date,contract_status,priority,contract_type,contract_no) values(?,?,?,?,?,?,?,?,?,?,?,?)::->[1366]Incorrect integer value: '' for column `crm`.`vtiger_servicecontracts`.`sc_related_to` at row 1
02/17/19 09:13:50,315 [22356] INFO VT  - function insertIntoEntityTable ServiceContracts vtiger_table name vtiger_servicecontractscf

**Comment by Archibald111** [comment]
We updated the demo and made a new install based on the actual GIT files and every thing works as expected.
