### ISSUE TITLE
BerliSoft Again not Working

### ISSUE THREAD

**Issue by GPS-WATCH** [berliCRM/berlicrm#242]
Hello,

fetched the latest changes on BerlISoftphone i don't know what is the matter now but. With old Style URL i got the two error's 

index.php?module=berliSoftphones&view=List&phonenumber=0049123456789
Permission to perform the operation is denied for name

withnew URL Style URL index.php?module=berliSoftphones&action=ListPhone&phone&phonenumber=0049123456789

i got {"success":false,"error":{"code":"Handler not found.","message":"Handler not found."}}

If i Manual added berlisoftphone to ws_entity again the first url style is working again.

**Comment by Archibald111** [comment]
thank you for your feedback, there will be a fix in the next release - the URL for the link has changed (see language file)
