### ISSUE TITLE
Bug Ckeditor

### ISSUE THREAD

**Issue by samprasamari** [berliCRM/berlicrm#290]
Drag images Upload success image but doesn´t display image with error
"HTTP error occurred during file upload (403: Forbidden)."

Check...
![2019-06-14 08 19 59](https://user-images.githubusercontent.com/51815286/59490819-82525200-8e7d-11e9-8dc2-e7c2e1b3cfe5.gif)

**Comment by Archibald111** [comment]
Your observation is correct, drag & drop is currently not supported, pls use the image icon of the editor
