### ISSUE TITLE
Decimal input not working anymore

### ISSUE THREAD

**Issue by NathanielBlack** [berliCRM/berlicrm#301]
Hi,

with the latest update we ran into the issue of not being able to input decimal numbers anymore. 
I cannot input the decimal number separator into fields because it says it's an invalid input. 

In this particular case we use it for tracking the hours of support tickets. All old tickets still have correct decimal hours like '0.5' or '1.75' however now I cannot input decimal numbers anymore.

**Comment by bbommer** [comment]
The validation of decimal numbers never really worked before, now be might have gotten a little overboard. I'll look into it. But please try to empty your browser cache, maybe some cached javascript causes the issue.

**Comment by NathanielBlack** [comment]
I just tried it with a different browser that has never seen the site before and it still does not work. 

Thank you for helping us out :-)

**Comment by NathanielBlack** [comment]
FYI: I also tried changing my decimal separator in the my user settings from the '.' to the ',' and afterwards I could not use a ',' either (which worked before because it was my group separator.)

**Comment by bbommer** [comment]
Yep, that's definitely broken. I just entered "1,5" hours (german format) which did validate but ended up as 15 hours in the ticket. There's a hotfix release planned for later today, if you're lucky we'll get it sorted until then.

**Comment by NathanielBlack** [comment]
That would really be great - thanks!

**Comment by SvenRoederer** [comment]
I've seen this also form some long time and I reported via direct conact. 
In the screenshots of https://github.com/berliCRM/berlicrm/issues/53 you can see that I had to use a "." as decimal separator back in August 2018.

**Comment by bbommer** [comment]
The initial issue should be fixed by latest commit.

Sven, unfortunately some older forms (mainly invoices and lineitems) don't support german number format yet (and it's a lot of work to fix).

**Comment by NathanielBlack** [comment]
Thanks @bbommer! I will give it a shot and report back if it did not work.
