### ISSUE TITLE
conflict between CRM-setting "upload_maxsize" and PHP-setting "upload_max_filesize"

### ISSUE THREAD

**Issue by SvenRoederer** [berliCRM/berlicrm#304]
I recently had a problem uploading a file of 3,5MB for attaching to a document. The file could be uploaded, but did not apprear in the document, without any notice.

changing the CRM-parameter ```upload_maxsize``` to 10MB raised teh limit displayed in the documents-bottom to 10MB, but the problem persists. I found the PHP-option ```upload_max_filesize``` was at 2MB and after changing to 10+MB the upload was successul. 

I suggest to combine the "max filesize" displayed at the documents-bottom to a test of both parameters mentioned above,

**Comment by bbommer** [comment]
Thanks for the valuable suggestion, which will be included in the next release.

**Comment by bbommer** [comment]
Will be part of next release, scheduled for monday.
