### ISSUE TITLE
Webservice Update does not seem to be working

### ISSUE THREAD

**Issue by NathanielBlack** [berliCRM/berlicrm#315]
Greetings, 

today I tried writing a small C# application making use of the 'webservice.php' API.
So far the Retrieval of objects worked flawlessly however now I want to programmatically update a ticket via the API and it always returns a 403 with the message 'Permission to perform the operation is denied for id'.
I tried doing it manually with Postman, which failed and now I tried it with C# Code (together with RestSharp) and it returns the same error. 

Is it broken right now or is there something wrong with the approach written about in these documents: 

- http://blog.crm-now.de/doc/rest/REST_Tutorial.pdf
- https://blog.crm-now.de/doc/rest/berliCRM/berliCRM_REST_API_Specification.pdf

I leave my POST-Request body empty and supply a whole JSON representation of the object in the 'element' query string parameter.

I would appreciate some help.

Best regards and thanks in advance!

**Comment by AlexKay85** [comment]
Greetings,

do you use an previously retrieved object as this request's element?
What exactly do you mean with leaving the POST-Request body empty?
Do you use an admin user or could your user lack update permission for that object?

This operation is not broken and the error message indicates a malformed object/request or, indeed, lacking sufficient user privileges.

**Comment by NathanielBlack** [comment]
Hi, 

thanks for the quick response. 

Yes I use the previously retrieved ticket object after changing one property value of it. 

And by leaving the POST Request body empty I mean that I only send this to the server:
POST https://***/webservice.php?operation=update&sessionName=xx&element={jsonHere}
All data is sent via query string parameters (which I find weird, but the documentation said so)

My session is the one of my admin account, so it should not be a problem with permissions.

**Comment by AlexKay85** [comment]
I see, this might be a bit misleading.

The request needs to be POST, otherwise the parameters won't be recognized.
So just target https://***/webservice.php and put the parameters in your POST body.

**Comment by NathanielBlack** [comment]
Oh my god! Thank you so much! 

Providing the parameters as a HTTP POST 'x-www-form-urlencoded' body made it work. 
The API documentation was a bit misleading there for me.

And thanks for the tip with the REVISE operation, I will check it out. 

You helped me a great deal, thanks! <3
