### ISSUE TITLE
Regular expressions don't work in Email-Converter rules to update tickets 

### ISSUE THREAD

**Issue by NathanielBlack** [berliCRM/berlicrm#331]
Hey,

in our BerliCRM we created a Email-Converter rule for incoming emails that's supposed to check if the Email is about an existing ticket and update this ticket's information accordingly. 

We try to match the subject of an email with a regex matching our ticket numbering pattern. 
We tried different versions of the regex, with and without capturing group(s) but none seemed to work. It does work when the ticket number is written at the end of the email's subject but not when its somewhere in the middle of the string.

I'd appreciate some insight on how a regex should look like that would work to update existing tickets. We verified all our expressions on regex101.com's php engine and they were valid.
I am not quite sure if it is our mistake or if it is a bug in the software. 

Thank you in advance and kind regards,
NathanielBlack

**Comment by Archibald111** [comment]
I suggest to look up the manual. There you can find an example which works. We have customers which use other expressions and so far we do not know of any bug.

**Comment by bbommer** [comment]
.. or provide a regex that didn't work. There's just too much that can go wrong with those.
Have all your attempts been with delimiters? IIRC you'll have to leave them out. Try (.*) instead of /(.*)/ f.e.
