### ISSUE TITLE
[Feature] German dateformat

### ISSUE THREAD

**Issue by NicolasGoeddel** [berliCRM/berlicrm#340]
Hi,

I just tried out the demo site: https://berlicrm.co.crm-now.de
And I am not able to switch to the correct dateformat. There are only the three styles the original vTiger offers. But I need `dd.mm.yyyy` and in the past I always had to change a lot of PHP and JS files and even had to write some new values into the SQL database. Actually, I assumed that berliCRM could also handle the German date format.

Please add that format to berliCRM. You can find a well written guide to add the format to vTiger 6.0 here: https://support.stefanwarnat.de/en:modifications:german-dateformat

**Comment by Archibald111** [comment]
the German date format is already used at some places, like PDF outputs and will become native in one of the next releases

**Comment by NicolasGoeddel** [comment]
@Archibald111 What do you exactly mean with next realeases? This issue has still no milestone, label or assignees. Would be nice so see an update here soon.

**Comment by NicolasGoeddel** [comment]
lol, after 3 years still no update. Well, at least I do not have to work with it anymore. ;-)

**Comment by Archibald111** [comment]
he was the only one who asked for it in many years
