### ISSUE TITLE
Import overwrites field "responsible"

### ISSUE THREAD

**Issue by ralphkretzschmar** [berliCRM/berlicrm#379]
Hi folks,

when i try to merge data (updating) with an import the field "zuständig" / "responsible" will be overwritten with "Administrator".

Can anyone help?

Best regrads

**Comment by Archibald111** [comment]
It works as describes in the manual. As long you do not have data for the assigned to field in your import data the current user will be used.

**Comment by ralphkretzschmar** [comment]
Thanks for the answer but:
I want to import additional data into existing accounts but the "Assigned User" gets overwritten. Is there any possibility to import additional infomation to existing accounts WITHOUT changing the existing user in "assigned to"?
Thanks for your help

**Comment by Archibald111** [comment]
add the assigned to field contents to your import data

**Comment by ralphkretzschmar** [comment]
so i have to export the assigned field from those accounts first
then merge it with the update information and then reimport it? correct?

**Comment by ralphkretzschmar** [comment]
could you tell me, where i can find these modifications to disable it?
i don't understand why a field is modified even it is not mentioned to be updated in the import file?

help appreciated :)

**Comment by ralphkretzschmar** [comment]
i've tried it with vt6.5 and the behavior is not the same. when i upate records with merge, the field "assigned to" is not touched - how expected.
if someone could give me a hint where to look at it would be great :)

**Comment by ralphkretzschmar** [comment]
if found the regarding problem in include/Webservices/VtigerCRMObject.php

around line 145 - its this part:
---------------------------------------

	public function revise($element, $meta){
		global $adb;
		$error = false;

		$error = $this->read($this->getObjectId());
		//crm-now: after read() the values will be in DB format, to save user format is expected, other functions (create(), update()) will always take values from request and sanitize those to user format
		$this->instance->column_fields = DataTransform::sanitizeForInsert($this->instance->column_fields, $meta);
------------------------------

after removing $meta & $this->instance->column_fields = DataTransform::sanitizeForInsert($this->instance->column_fields, $meta) it is working as expected :)

**Comment by AlexKay85** [comment]
Greetings,

thank you for your input.
We've provided a fix (https://github.com/berliCRM/berlicrm/commit/06cea75a6f222afe406dc5c54d81a499c705a038) for this issue.
sanitizeForInsert() expects id values in Webservice format but when values of the original object are read the values won't have any Webservice prefixes.
Same as with other reference fields we will skip conversion now.
