### ISSUE TITLE
Foldername not sorted by Name for adding Documents

### ISSUE THREAD

**Issue by GPS-WATCH** [berliCRM/berlicrm#419]
Hello,

when Adding a new Document, the folernames are not sorted by name.

![2020-03-25 10_19_52-Dokumente](https://user-images.githubusercontent.com/43584688/77521062-63f49a80-6e82-11ea-89df-5d7770882060.png)

**Comment by urban-thinking** [comment]
confirmed (y)

**Comment by urban-thinking** [comment]
Solved.
