### ISSUE TITLE
RSS Feed show only null not news

### ISSUE THREAD

**Issue by GPS-WATCH** [berliCRM/berlicrm#425]
Hello

i have issue  with some RSS Feed ive added a source to you Demo same result please check

https://berlicrm.co.crm-now.de/index.php?module=Rss&view=List&id=9

**Comment by urban-thinking** [comment]
Hiya,

could you explain the "issue" a little bit more pls?

regards

**Comment by GPS-WATCH** [comment]
you can test it on your Demo site i added the Link? when you click on one of the Messe feed scroll down to see se site but the is no site only NULL

**Comment by urban-thinking** [comment]
Hmm,

might be a problem with the selected feed ... I added another feed, which works fine.

Have a look yourself:

https://berlicrm.co.crm-now.de/index.php?module=Rss&view=List&id=11

regards

**Comment by GPS-WATCH** [comment]
i see it is working but a lot of feeds do not like this github feed from you repo

ive added a other feed what is from your repo

https://berlicrm.co.crm-now.de/index.php?module=Rss&view=List&id=12

**Comment by urban-thinking** [comment]
OK ... we dive in. Stay tuned ...

**Comment by urban-thinking** [comment]
Pls have a look at #426 ...

**Comment by GPS-WATCH** [comment]
great
