### ISSUE TITLE
E-Mail Ticket Creation Ä Ö Ü for Variable

### ISSUE THREAD

**Issue by GPS-WATCH** [berliCRM/berlicrm#428]
Hello,

with the New PHP Mailer a little issue ocours on Ticket Creation. For Example when a variable from  name is in in $contact_id | $parent_id.

We Have a Workflow that fire E-Mail and in the Topic of the E-Mail is the Name of the Ticket Issuer this  name will be for a ö = &ouml;

again this issue ocours only when we have a variable in E-Mail Topic $contact_id | $parent_id normal words in that E-Mail Topic with ö ä ü will work like a charme.

Also the Issue will shown up in widget section of renetly change items but only for entry of event not in the Mail text as well.

with the old mailer it works without issue

**Comment by urban-thinking** [comment]
#429 fixed
