### ISSUE TITLE
Rabatt Calculation on overview of Quotes does not Work

### ISSUE THREAD

**Issue by GPS-WATCH** [berliCRM/berlicrm#433]
Hello,

when i set up for example 10% Rabatt for an Item it does not show up in overview of the quote
![2020-05-06 02_04_20-Window](https://user-images.githubusercontent.com/43584688/81127419-6bf23080-8f3e-11ea-9993-8dd0b648b615.png)

**Comment by urban-thinking** [comment]
Hiya,

the lower field is not an "overview" field for discounts of the line items. It's a field of it's own where you can enter a total discount.

kind regards

**Comment by GPS-WATCH** [comment]
Ah okay sorry for the wrong alert
