### ISSUE TITLE
Email with BerliCRM Document cuts text

### ISSUE THREAD

**Issue by apaeffgen** [berliCRM/berlicrm#443]
In Berlicrm 1.0.24 sending an email with an attached BerliCRM Documents is copied correctly to the send folder in BerliCRM.

But the text is not seen by the recipient. If you watch the source code of the email, the text is there. But it is not shown to the recipient.

He just sees the attachment. You can check it with an imap server, that also copies the sent email to the sent folder.
Unfortunately, in  Berlicrm, when you check the attached text to "Leads" is shows up correctly.

**Comment by urban-thinking** [comment]
Hiya,

> He just sees the attachment. You can check it with an imap server, that also copies the sent email to the sent folder.
> Unfortunately, in Berlicrm, when you check the attached text to "Leads" is shows up correctly.

could you please attach a screenshot of the problem?

kind regards

**Comment by apaeffgen** [comment]
Hi,
Attached is a screenshot of an example.

1. Screenshot is in BerliCRM
2. Screenshot is the recipient in Apple Mail (It is readable)

In Thunderbird it is shown correctly as well.
In some Webmailer like Horde, it has the same problems like BerliCRM.

Seems a rendering problem in the php code.

Best regards
Andreas Päffgen


It just makes the user insecure, what

**Comment by apaeffgen** [comment]
Some more information about the topic.

It seems that a email, that is copied to the send folder has this problem (Maybe this copy gets corrupted?)

Attached is a screenshot of the inbox of horde.(This is the recipient) This works. The copy in the send folder (not a test) is blank. There is the second screen shot.

**Comment by urban-thinking** [comment]
Unfortunately ... we cannot see any screenshots :-/

**Comment by apaeffgen** [comment]
They had been attached to the email.

Do you get the email directly, or is it just posted on GitHub?

**Comment by urban-thinking** [comment]
We see only the posts here ... you can add screenshots when posting here using the GUI.

**Comment by apaeffgen** [comment]
<img width="972" alt="Bildschirmphoto-E-Mail 2020-08-26 09-37-57" src="https://user-images.githubusercontent.com/426561/91301494-4ca93880-e7a5-11ea-8c79-ffc785ec268f.png">
<img width="674" alt="Bildschirmphoto-Papierkorb (60 E-Mails) 2020-08-26 09-38-41" src="https://user-images.githubusercontent.com/426561/91301531-5e8adb80-e7a5-11ea-8167-890fe68df9bd.png">
<img width="691" alt="Bildschirmphoto-Monosnap 2020-08-26 14-08-06" src="https://user-images.githubusercontent.com/426561/91301731-af9acf80-e7a5-11ea-93dc-5b30791b1042.png">

See the attached images

**Comment by urban-thinking** [comment]
OK, we got the problem. Now checking ...

**Comment by Archibald111** [comment]
solved with https://github.com/berliCRM/berlicrm/pull/619
