### ISSUE TITLE
E-Mail Converter doesn't save Folders

### ISSUE THREAD

**Issue by darnhold** [berliCRM/berlicrm#457]
The E-Mail Converter doesn't save Folders in Database.
He is also not able to scan the folders as well.
When i add a Folder manually to database, he mainly grab the mails, but doesnt mark the e-mails as read.

![image](https://user-images.githubusercontent.com/13847207/94589062-1455b800-0285-11eb-920c-0097d1c5199b.png)
![image](https://user-images.githubusercontent.com/13847207/94589095-20da1080-0285-11eb-834e-b894f122b337.png)

**Comment by Archibald111** [comment]
looks to me like an installation error (Umlaute), pls. check the installation requirements

**Comment by darnhold** [comment]
> looks to me like an installation error (Umlaute), pls. check the installation requirements

Is there a way for fixing it either?
The Umlaute are imported by the programm in IMAP out of the linked mailbox.

**Comment by Archibald111** [comment]
Unfortunately we are unable to reproduce your issue
