### ISSUE TITLE
Quick create events in calendar problem

### ISSUE THREAD

**Issue by samprasamari** [berliCRM/berlicrm#464]
Hello All.

Quick create events in calendar not working for custom fields.

To reproduce:
In events module add a new field and set to QuickCreate.

Go to calendar and create an Event in QuickCreate Mode.
Set or fill the new field previously created and press save.

Result:
All fields will be filled but custom field will be empty

**Comment by Archibald111** [comment]
thank you for this report, we will look into that

**Comment by samprasamari** [comment]
@Archibald111 Thanks. If you need further information or provide a demo instance, i can reproduce the bug.

**Comment by samprasamari** [comment]
Solved. Wrong uitype.
