### ISSUE TITLE
Asset/Bestand: help-text for sale-date 

### ISSUE THREAD

**Issue by SvenRoederer** [berliCRM/berlicrm#473]
HI I just realized a mismatch between the "saledate" field of the asset-management and the relating helptext (at least in German language).
The field is defined as "date entered must be today or before" the help-text is "should be today or before"

![Screenshot 2020-12-10 080949](https://user-images.githubusercontent.com/1755362/101733406-1f1b9d00-3abf-11eb-905e-b01d34e8ce71.png)

This should match to each other.

**Comment by urban-thinking** [comment]
Hiya Sven,

thanks for your note.

Basically you're right, however the German "sollte" is quite near to the English 'must' ... but in a little mor friendy manner. So we choosed it itentionally. You can change it in your translation file as you like.

Kind regards.
