### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by NicolasGoeddel** [berliCRM/berlicrm#475]
Hi,
on the [installation page](https://blog.crm-now.de/doc/berliCRM/installation/Installation_berlicrm.html) there is a very small chapter at the end about updating the CRM:

- get a diff and update all berliCRM files which had been modified or added, this will apply all file changes

From where do I get that diff? I am running version 1.0.0.22 currently and I want to update to 1.0.27 now. I don't know why I have a four-numbered version number and the latest version has a three-numbered version number but however. I am looking for a better guide for updating berlicrm. In the official forum I never got an answer to [my question](https://forums.berlicrm.de/forums/topic/upgrade-to-v1-0-24/). So I will try my luck here.

This is the footer of my current installation:
![grafik](https://user-images.githubusercontent.com/1520064/101771583-75ea9c00-3aea-11eb-8965-ab222bebdbef.png)

**Comment by Slaburai** [comment]
Hi, i always made an backup of all files and the db first. Then i copied all files into my crm directory and after that i runned the yourcrm.tld/db_update.php. With a backup in mind, you could try to update to the newest version in one step safely.
