### ISSUE TITLE
Compatibility with PHP 7.4

### ISSUE THREAD

**Issue by NicolasGoeddel** [berliCRM/berlicrm#476]
Hi,
when can we except a compatibility to PHP 7.4?

PHP 7.2 will reach its end of life with the end of this year. PHP 7.3 is not supported yet if the [installation page](https://blog.crm-now.de/doc/berliCRM/installation/Installation_berlicrm.html) is right:
![grafik](https://user-images.githubusercontent.com/1520064/101771956-ff01d300-3aea-11eb-8725-20e281774aea.png)

PHP 7.4 is one of the latest versions, PHP 8.x has just become available.

It would be nice to be able to upgrade to the latest PHP 7.x branch.

**Comment by Slaburai** [comment]
Hi, i have no issues with PHP 7.4. so far (1.0.2x)

**Comment by Archibald111** [comment]
latest Release [v.1.0.36] provides PHP v.7.4 compatibility
