### ISSUE TITLE
Can not save calendar feed type

### ISSUE THREAD

**Issue by samprasamari** [berliCRM/berlicrm#496]
Hello all,

With this change #488 , cannot save state of calendar feed type.
It updates the feed but doesn't save state. (Active or Inactive)

**Comment by AlexKay85** [comment]
> 
> 
> Hello all,
> 
> With this change #488 , cannot save state of calendar feed type.
> It updates the feed but doesn't save state. (Active or Inactive)

Hi,

it was intentionally left out but I agree that the feed selection should be cached, so we reverted the change with: https://github.com/berliCRM/berlicrm/commit/e49972ba20b327029d3a9ac8fed88f35635fd7c9

**Comment by samprasamari** [comment]
Thanks, That's great

**Comment by samprasamari** [comment]
Hello @AlexKay85 , thanks. 
Just found one bug with this.
In Shared Calendar, doesn't save the Visibility of the users Calendar.
Let's say you disable in SharedCalendar User "Mine", If you refresh the page, user "Mine" still disabled but events are loaded.
