### ISSUE TITLE
Installation stuck at "initializing database"?

### ISSUE THREAD

**Issue by ZARazor91** [berliCRM/berlicrm#502]
Hello,
we're trying to install berliCRM on a server in our company, we enter all the required credentials, everything is marked as fine and as soon as it's installing, nothing else happens. When we tried vtiger before we had a loading screw (or however it's called, i'm german) and now we don't have anything at all (marked with the arrow on the screenshot). He creates the database (if wanted) but nothing else happens.

I saw in the Index.php of the install routine, that the part, where they create all the tables and stuff, is marked as a comment but i guess it's intended.

Is it normal that i don't see any progress or is maybe something wrong with it? I'll also include the index.php (wth .txt on the end because of github) from modules/Install/views.
[Index.php.txt](https://github.com/berliCRM/berlicrm/files/5957003/Index.php.txt)
![Unbenannt](https://user-images.githubusercontent.com/3112532/107489477-f1b7a200-6b88-11eb-9e8a-049b493a5132.PNG)

**Comment by Archibald111** [comment]
You wrote that you entered all the required credentials but have you checked your server's configuration so that it matches all required settings?

**Comment by ZARazor91** [comment]
Is it maybe because i tried it with php7.4? as most of the php-packages that are required aren't available anymore for php7.1 and php7.2. Because i saw that it's working for others with 7.4.

**Comment by urban-thinking** [comment]
Also ... always use https ... not http.

**Comment by ZARazor91** [comment]
> Also ... always use https ... not http.

Yes i know that it's not good at all to use http, it's a thing that i should ask my supervisor because for internal stuff we don't use it at all somehow... Only when reachable from outside

**Comment by urban-thinking** [comment]
Not using https might be the reason for your install problem ... the installer is somewhat picky :-/

**Comment by ZARazor91** [comment]
Okay good to know, i'll try if it fixes the problem and then report

**Comment by ZARazor91** [comment]
Okay it fixed my problem, as soon as i enabled https it worked.
