### ISSUE TITLE
bad formating of currencies in "Einkaufsbestellung"

### ISSUE THREAD

**Issue by SvenRoederer** [berliCRM/berlicrm#53]
In the Module "Einkaufsbestellungen" there are some currency-fields where the decimal part is not always 2 digits.
In the Screenshot you can see 2 fields where "€ 141.3" is printed, but "€ 141.30" is expected.

![berlincrm - einkaufsbestellung - format of currency](https://user-images.githubusercontent.com/1755362/44849247-cf03ce00-ac59-11e8-8c1b-764b01aab973.png)

**Comment by SvenRoederer** [comment]
it seems to be only bad in the "edit"-view. When I open the page in the "view"-Mode the formatting is fine, tailing zeros and correct separators.
![berlincrm - einkaufsbestellung - format of currency in view-mode](https://user-images.githubusercontent.com/1755362/45021836-df89bf00-b032-11e8-8ce1-fade8284fe23.png)

**Comment by bbommer** [comment]
Thanks, fixed.
