### ISSUE TITLE
Workflow Conditions changed with more than hours later

### ISSUE THREAD

**Issue by BastyJuice** [berliCRM/berlicrm#582]
Hello,

if you make a workflow with conditiuons changed and as example more than 10 hours later workflow is not working

please have a look at this issue

**Comment by urban-thinking** [comment]
Hello BastyJuice,

unfortunately we cannot process your request ... because we really do not understand it.

Could you elaborate on that?

**Comment by BastyJuice** [comment]
oh sorry so in this case that is better by picture this conditions for example is not working

![2021-09-07 16_54_42-Workflows](https://user-images.githubusercontent.com/13349817/132366390-3da7d76f-431f-48d6-b934-3ab84e305cd8.png)

**Comment by BastyJuice** [comment]
all conditions with modified time are not working

**Comment by BastyJuice** [comment]
yes i can

![2021-09-07 17_02_26-Workflows](https://user-images.githubusercontent.com/13349817/132367594-d5831634-081d-46e9-9298-ef10174a3d2a.png)
![2021-09-07 17_03_12-Workflows](https://user-images.githubusercontent.com/13349817/132367615-4c244ac1-0419-4cb5-ab4a-51c37a9f2203.png)

**Comment by Archibald111** [comment]
tested it with latest release and it works as expected
