### ISSUE TITLE
Bithday from Contactrs not Showing up in Calendar

### ISSUE THREAD

**Issue by BastyJuice** [berliCRM/berlicrm#584]
Hello,

found a little Bug, the Birthdays from Contacts are not Showing up in Calendar anymore i know this was working in the past

best regards

**Comment by AlexKay85** [comment]
Hi,

could you provide some more details, please? A quick test with an admin-User shows no issues.

Is the logged-in user able to see the Contact, are Birthdays checked on the left side as activity types to display?

**Comment by BastyJuice** [comment]
Yes you can check this too ive added B-Day in your Demo for Katrin Lorra, but it showing not up in Calendar :-)

**Comment by AlexKay85** [comment]
That Contact belonged to a group (has been changed for testing purposes) and that group members are assigned by a role, not individual users.

Calendar Feed.php getGroupsIdsForUsers() method uses GetUserGroups getAllUserGroups() method which doesn't return any group IDs for that Guest user.

So when the query in pullContactsByBirthday() checks for ownership, it will only return Contacts of that Guest user.

**Comment by BastyJuice** [comment]
okay but in our own it doees not working too is it working for your crm?

**Comment by AlexKay85** [comment]
That depends what you expect.

You could argue that Contacts should be displayed if they belong to a group the logged-in user is a part of by role.

But that functionality hasn't changed as far as I can tell.

**Comment by BastyJuice** [comment]
So all our Member all in the same Group this Contact is under control of this group but why they are not showing up?

**Comment by AlexKay85** [comment]
I just checked for the demo system berlicrm and the Guest user is actually of the role 'Geschäftsführung' and not 'Vertriebsmanager' or 'Vertriebsbeauftragter' that define the group 'Vertriebsteam', that's why no Contacts are displayed in the Calendar for that user if a Contact belongs to the group.

As for why it doesn't work in your system I cannot say as I don't know about your user, group and role structure.

**Comment by BastyJuice** [comment]
Ok

can you show me Screeen shot that i can apply that for us too? i Havee A Group --ALL-- that my User is Part of and The Contact is Manged by Group --All--

whats now wrong=

**Comment by BastyJuice** [comment]
okay i think i understand now the contact has to be assigned to a person not a group to bevissible, but if the peson is mangend by a group and the user is part of the group why the birhday is not showing up ?

**Comment by BastyJuice** [comment]
found issue thanks for help :-)
