### ISSUE TITLE
ModComments Bug no reply Tree View with Latest Code

### ISSUE THREAD

**Issue by BastyJuice** [berliCRM/berlicrm#588]
Hello somthing happend with ModComments in latest Code.

Normaly you can do a new comment and a reply to a comment but with latest code you can reply to a comment but i will not show anymore as tree everytime now it is a new comment can you fix that please?

In the past releasee it was tree view, this bug is present in all ModComments Modules

![2021-09-17 09_33_33-Leads](https://user-images.githubusercontent.com/13349817/133743144-5ef44e25-8e69-4f5b-91b4-ce4d21c741bd.png)

**Comment by urban-thinking** [comment]
Hmm ... could you send a screenshot of the "old" behavior?

If you click on "Detail view", you can still see the hierarchy / tree.

**Comment by BastyJuice** [comment]
it was in the same frame when you hit reply / erweitern now it is a seperate comment that is confuising becouse you cant comment to a comment

![2021-09-17 12_42_03-Leads](https://user-images.githubusercontent.com/13349817/133770095-31acd32d-8403-4a8e-a97d-a17203195d43.png)
nt203195d43.png)

**Comment by Archibald111** [comment]
ich kann da kein Problem erkennen, in unserer Demo ist das noch da
![comments](https://user-images.githubusercontent.com/35070928/133774303-554629ef-5b9c-4596-8b15-e131f7c495a5.png)

**Comment by BastyJuice** [comment]
> ich kann da kein Problem erkennen, in unserer Demo ist das noch da
> ![comments](https://user-images.githubusercontent.com/35070928/133774303-554629ef-5b9c-4596-8b15-e131f7c495a5.png)

you are right, in commets menu from the module yes but not in the main quick menu that is gone

**Comment by urban-thinking** [comment]
Hmm .. I checked the berliCRM 1.0.0.28 and the behavior is exactly the same as now.

@BastyJuice You are right, in the "main quick menu" there is no hierarchy shown ... but it never was!

**Comment by BastyJuice** [comment]
> Hmm .. I checked the berliCRM 1.0.0.28 and the behavior is exactly the same as now.
> 
> @BastyJuice You are right, in the "main quick menu" there is no hierarchy shown ... but it never was!

okay maybee i will getting old :-)
