### ISSUE TITLE
Responsive Theme

### ISSUE THREAD

**Issue by cristo1985** [berliCRM/berlicrm#605]
Hi, is there a responsive theme for berlicrm?
It's based on vtiger?
Thanks

**Comment by urban-thinking** [comment]
> Hi, is there a responsive theme for berlicrm?

AFAIK there is no them option in berliCRM.

> It's based on vtiger?

Yes.

**Comment by Archibald111** [comment]
crmtogo interface for mobile devices

**Comment by cristo1985** [comment]
it's suck
