### ISSUE TITLE
Einrichtung des Mail Managers wirft Fehler

### ISSUE THREAD

**Issue by muellpanda** [berliCRM/berlicrm#702]
Hi zusammen,

bei der Einrichtung des Mail Managers bekommen wir Fehlermeldunen.
Folgende Einstellungen haben wir vorgenommen:
![image](https://user-images.githubusercontent.com/49154139/173366106-517fab83-55e4-4311-b223-f0b1777446e0.png)

Dabei erhalten wir den folgenden Fehler (egal ob TLS oder SSL ausgewählt ist):
![image](https://user-images.githubusercontent.com/49154139/173367139-da1c57dc-25c7-45cb-b4cf-14eace0739d7.png)

Es sieht kurzzeitig so aus, als würde der Loginvorgang an sich klappen, man sieht kurz "Lade INBOX", gefolgt vom Fehler. Gibt man ein falsches Password an, kommt man nicht so weit.

Wir haben zwei verschiedene Mailserver ausprobiert, bei beiden bekommen wir die gleichen Fehlermeldungen.
Wir verwenden Berlicrm v1.0.33 in einem Docker-Container mit dem image `php:7.3-apache`.
Der Mailversand (SMTP Einstellungen) funktioniert hingegen.

Das Issue https://github.com/berliCRM/berlicrm/issues/677 haben wir gesehen, die vorgeschlagene Lösung das Passwort auf 15 Zeichen zu reduzieren hat bei uns *nicht* geholfen. WIr vermuten an der Stelle ein anderes Problem.

**Comment by AlexKay85** [comment]
Hallo,

das sieht mir sehr nach dem Verhalten aus, dass die Zugangsdaten nach erfolgreichem Login-Test nicht abgespeichert werden konnten.
Die Gründe dafür sind folgende:
- durch die Umstellung der AdoDB Klasse funktionieren implizite Typenumwandlungen nicht mehr wie vorher
- das Datenbank-Feld erwartet einen Integer, bekommt aber einen leeren String geliefert, was durch STRICT_TRANS_TABLE abgeblockt wird

Der Fix für das konkrete Problem sollte unter https://github.com/berliCRM/berlicrm/commit/78e0d9e6d939000a6ab9fcc4d35c6d446e107b57 zu finden sein, aber es ist dennoch wichtig zu überprüfen, ob der Datenbank-Server STRICT_TRANS_TABLE aktiviert hat und dieses ggf. zu deaktivieren, denn es kommt sonst noch an anderen Stellen zu Problemen.

**Comment by sr-verde** [comment]
Main branch und `STRICT_TRANS_TABLE` ausschalten und nicht mehr als 12 Zeichen als Passwort helfen. :+1: Danke euch.
