### ISSUE TITLE
Installation instructions still up to date?

### ISSUE THREAD

**Issue by SpoonOfDoom** [berliCRM/berlicrm#804]
Hi, I'm currently setting up a berliCRM instance, and I was wondering if the installation instructions (linked at https://blog.crm-now.de/doc/berliCRM/installation/Installation_berlicrm.html) are even still up to date? It says for example that MySql 5.5 or 5.6 are recommended, and that 5.7 isn't even tested "yet". However, 5.7 has been out since 2015 and is nearing EOL, and 5.5/5.6 are already far beyond that (see for example https://endoflife.date/mysql). That makes me wonder if the instructions are just out of date? Or has there never been any effort to move towards newer versions? Or is the focus instead on MariaDb?

**Comment by Archibald111** [comment]
the installation instructions are uo to date, we are working on updates
